version: '3.7'
services:
  app:
    image: node:10
    volumes:
      - ./:/app
    working_dir: /app
    command: sh -c "yarn && yarn prisma tmp-prepare && yarn ts-node main.ts"
    environment:
      - DATABASE_URL=postgres://prisma:prisma@postgres
    depends_on:
      - postgres
  postgres:
    image: postgres:10.12
    restart: always
    environment:
      - POSTGRES_USER=prisma
      - POSTGRES_PASSWORD=prisma
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
